  [site]
  title = "Brad Montgomery"
  url = "https://bradmontgomery.net"
  author = "Brad Montgomery"
  subtitle = "a blog about tech, bikes, and occasionally food"

  [build]
  templates_dir = "templates"  # optional custom templates
  static_dir = "static"        # optional, defaults to "static"
